### ISSUE TITLE
Support generating iframes with a `title` attribute

### ISSUE THREAD

**Issue by reefdog** [nprapps/pym.js#101]
[Section 508](http://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/#prI) and [WCAG 2.0](http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/2_4_1) both require frames/iframes to have identifying `title` attributes; Pym-generated iframes currently don't.

Suggestions:

1. Let `title` be passed in on the `config` (my preference)
2. Pick up the containing `div`'s `title`

Have a preference? I'm willing to contribute a patch if you'd like.

**Comment by onyxfish** [comment]
Interesting! I'm happy to support this case. I agree that number 1 is preferable. Happy to apply a patch if you send one!

**Comment by eads** [comment]
Our apologies for not getting back to this. I'll evaluate the PR but I'm all good with this addition.

**Comment by reefdog** [comment]
No prob @eads. We designed our way around needing Pym anyway, but I imagine this will be useful for others. You might consider letting people config [the `sandbox` attribute](http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/), too.
