### ISSUE TITLE
ColdFusion and WordPress

### ISSUE THREAD

**Issue by rayvision** [nprapps/pym.js#112]
I'm trying to iframe a coldfusion page onto a WordPress blog. The blog that I'm working with is:

http://nationwide.rayvisiondesign.com/Sell-My-Note/sellmynotequote3b/

The page that I'm trying to iframe in is:

http://www.nationwidesecuredcapital.com/wpsellmynotequote_1a.cfm

This doesn't seem to be working properly, I've tried testing the page in the PymViewer, and unless the page is full screen, the content isn't working responsively. Would appreciate any help to solve this issue and see what I'm doing wrong.

Thank you,

-Ray

**Comment by eads** [comment]
There is something wrong with the parent pym.js file. See http://nationwide.rayvisiondesign.com/Sell-My-Note/pym.js -- there are a bunch of random bad characters.
