### ISSUE TITLE
xdomain example causes console error 

### ISSUE THREAD

**Issue by ChrisBAshton** [nprapps/pym.js#124]
Using the docs example code... http://blog.apps.npr.org/pym.js/#examples

```js
var pymParent = new pym.Parent(iframeUid, iframeUrl, { xdomain: '*\.npr\.org' });
```

...leads to this error:

`Uncaught SyntaxError: Invalid regular expression: /*.npr.org$/: Nothing to repeat`

**Comment by jjelosua** [comment]
@ChrisBAshton We are actively working on a new release (1.0.0) that should be delivered by the end of  August where we are going to improve docs. Thanks for letting us know that this example is not working, we will take a look at that.
