### ISSUE TITLE
Pym.JS fails if an iframe already exists in the container

### ISSUE THREAD

**Issue by ChrisBAshton** [nprapps/pym.js#125]
We just had a (very difficult to debug!) issue whereby iframes (inserted by Google ads) were automatically appended to our empty container div, BEFORE we managed to invoke Pym.

This line of code then failed:

https://github.com/nprapps/pym.js/blob/master/src/pym.js#L335

...as it would send a postMessage to the ad iframe, rather than our application iframe.

We fixed this by adding a `pym-iframe` class to the created iframe, and looking via class name rather than tag name. I've opened a PR: https://github.com/nprapps/pym.js/pull/126

**Comment by jjelosua** [comment]
Hi @ChrisBAshton, I am curious about this, Are you using data-attributes or are you manually invoking pym later on?

I thought your issue was related to something that we want to change for the 1.0.0 release but I am not sure if our approach will solve the problem. The idea is to replace the contents of the container div instead of appending to them when the parent constructs the iframe. You can preview our almost certainly final approach here https://github.com/nprapps/pym.js/blob/hearken-and-tests/src/pym.js#L226-L230

**Comment by ChrisBAshton** [comment]
We manually invoke Pym, somewhere below our container div. Here's a diagram:

![68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f31582d50773977525a475466364e3665487955436b3534566f4c5a35695248553630794551316876596c57632f7075623f773d3139333426683d31303033](https://cloud.githubusercontent.com/assets/5111927/17518814/44acd782-5e41-11e6-889d-300571e9fa9c.png)

The CMS we're using injects advert iframes in an almost random fashion; sometimes this means inside our placeholder div.

e.g. initial page structure

```html
<div class="main-container">
    <div class="iframe-container"></div>
</div>
```

Advert JS happens:

```html
<div class="main-container">
    <div class="iframe-container">
        <iframe class="advert" src=""... />
    </div>
</div>
```

Pym gets invoked by our inline JS....:

```html
<div class="main-container">
    <div class="iframe-container">
        <iframe class="advert" src=""... />
        <iframe src="my-custom-app.html" />
    </div>
</div>
```

Pym sends a predefined message to our iframe - only it doesn't, because it sends it to the first iframe in the `iframe-container`. Hence the bug.

It sounds like the new proposed Pym solution will clear the placeholder entirely - which will (in this case) remove the advert iframe too?

**Comment by jjelosua** [comment]
Hi @ChrisBAshton,
We recommend to instantiate pym as soon as possible after the container element is created to avoid this situations, but in some situations that is not possible. In our proposed solution we will make sure that the placeholder will only include the pym managed iframe so yes it will remove the advert iframe in your case....would that be a problem?

**Comment by jjelosua** [comment]
@ChrisBAshton I think that requiring the placeholder to be empty in order for the library to work with it is an understandable/reasonable requirement

**Comment by coreyhaines** [comment]
@ChrisBAshton what CMS is this? That's pretty strange that it would just place the ad in whatever div it feels like.
The new version of pym does remove all child elements of the placeholder div before inserting the iframe. This is to support CMSes that don't render empty tags, so we put a placeholder, such as `_` there.

**Comment by ChrisBAshton** [comment]
No problem, I see it as a reasonable requirement too. I've raised it with the necessary product people in our team; unpredictable injection of adverts is a risky game!

That said, is there a reason why we're using `getElementsByTagName` rather than selecting by class name? Applying a class to the generated iframe gives more freedom for Pym users to style or programmatically interact with it. (I may just have answered my own question!!)

**Comment by jjelosua** [comment]
@ChrisBAshton I am closing this issue for now
