### ISSUE TITLE
Document use of `title` attribute

### ISSUE THREAD

**Issue by ChrisBAshton** [nprapps/pym.js#127]
I didn't realise Pym.js actually supports the `title` attribute of the iframe - I can see it was added as a result of: https://github.com/nprapps/pym.js/issues/101

But do a `CMD + F` on 'title' on http://blog.apps.npr.org/pym.js/ and it returns nothing! Can we update the docs please? Thanks

**Comment by jjelosua** [comment]
@ChrisBAshton Hi Chris we are going to improve docs for the 1.0.0 release at the end of August. Will make sure we add title to the docs by then

**Comment by jjelosua** [comment]
duplicate of #115
