### ISSUE TITLE
parent.sendMessage does not work if second argument is falsey value

### ISSUE THREAD

**Issue by biegel** [nprapps/pym.js#132]
It appears that if you use certain "falsey" values for the second parameter in the ```sendMessage``` call from the parent page, the message event handler on the child page doesn't fire.  Though the values ```0``` and ```false``` seem to work for some reason.

To reproduce:

**On parent page:**
```
var pymParent = new pym.Parent("iframe_id", "/iframe", {});
window.document.onclick = function(e) {
  pymParent.sendMessage('testMessage'); // won't fire
  pymParent.sendMessage('testMessage', undefined); // won't fire
  pymParent.sendMessage('testMessage', null); // won't fire
  pymParent.sendMessage('testMessage', ""); // won't fire
  pymParent.sendMessage('testMessage', 0); // fires
  pymParent.sendMessage('testMessage', false); // also fires
  pymParent.sendMessage('testMessage', {}); // other values seem to always fire
};
```

**On child page:**
```
var pymChild = new pym.Child({});
pymChild.onMessage('testMessage', function(args) {
  console.log(args);
});
```

The message handlers should be able to handle all arguments.  We're passing a plain old ```{}``` at the moment to work around the bug.

**Comment by jjelosua** [comment]
Hi @biegel sorry for not getting you back sooner, I have been able to reproduce your problem and have tweaked a couple of regex to allow for empty messages. You have it fixed on master. We will make a release soon, but with elections it can all be pushed back a bit.
