### ISSUE TITLE
Make safe for universal rendering

### ISSUE THREAD

**Issue by quickhand** [nprapps/pym.js#146]
I do universal rendering of my site with a node, React, webpack/babel setup. On the server side, my import fails because "document" is not defined. I don't use pym on the server-side (I only use it in react's componentDidMount handler), but I need the library not to fail if "document" is not defined (so that I can reuse my code). I believe it's a simple matter of changing the following line for the npm packaged version:

lib.autoInit();

to

if(typeof document !== "undefined") {
    lib.autoInit();
}

or something similar.

**Comment by eads** [comment]
Makes sense to me -- Pym's javascript is a little old skool at this point; would be good to integrate better with webpack etc.

**Comment by quickhand** [comment]
What I suggested was one solution, but ideally, an imported npm package should define but not execute code at all, regardless of whether "document" is defined. It could export an "autoInit" function, but not execute it until the developer decides.

**Comment by jjelosua** [comment]
@quickhand Sorry for the silence....I have found a slot to take a look at `pym` again and check issues and PRs. I will be actively working on a new release 1.2.0 for mid March. Your suggestion will be included in that release. Even though I understand and can even agree on your opinion of having code executed automatically can lead to some issues, there are benefits in that approach (pym.js is embedded in many different configurations, many of which have important restrictions on what can be included on the parent page, and having pym automatically executing autoInit on the parentPage simplifies the workflow a lot for some of our users).

Anyhow we will remove the execution if there's no `document` to allow for clean builds on the server side. Thanks for pointing that out to us. and stay tuned...
