### ISSUE TITLE
angular import

### ISSUE THREAD

**Issue by brusand** [nprapps/pym.js#156]
Hi All,

Sorry for a newbie question but i done an npm install pym.js@1.2.2 but i can't import the pym module.

i code : import pym from '../../../node_modules/pym.js/dist/pym.v1.js'; but can't find any pym module !

is someone had integreted pym.js in an angular app ?

Thx
Best regards
Bruno

**Comment by davidgg** [comment]
Hi!

I know this is old, but for anyone asking the same:

`
import * as pym from 'pym.js'
...

pymChild = new pym.Child();
`
