### ISSUE TITLE
iFrame is has a minimum height

### ISSUE THREAD

**Issue by travis-john** [nprapps/pym.js#158]
I'm having an issue where I have example content that is less than 150px(which seems to be the minimum height) and the iframe is not automatically resizing, even with pymChild.sendHeight. I would use polling, but we don't want the sizing delay. We want the iFrame at the correct size on page load.

Any suggestions?

**Comment by jjelosua** [comment]
Hi @travis-john Does that example live somewhere that we can check out? Or can you provide a basic jsfiddle example with the issue you are facing? there's no limit on the minimum height that is enforced on the iframe so that should not be an issue.
