### ISSUE TITLE
IFrame height is 0 when loaded !!!

### ISSUE THREAD

**Issue by lolziac** [nprapps/pym.js#160]
Dear community,

I have an issue implementing openspending embedded code to my platform using pyc.js .
Here is a [jsfiddle](https://jsfiddle.net/0wvsxda3/) example

The child page has this code:
```
<script src="https://pym.nprapps.org/pym.v1.js" type="text/javascript"></script>
  <script>
      var pymChild = new pym.Child();
      pymChild.sendHeight();
  </script>
```
When page loads, it will set the iframe height 0 
if you just resize the page it will get the height value correctly, can somebody help me fix this issue that is triggering the height to 0 at load.

EDIT: If I use on the child page polling then it reloads good, I think this would do but im now curios to know why it is sending it with height 0 even when sendHeight() is set
```
var pymChild = new pym.Child({ polling: 1 }); 
```

keep the good job (I desperately want pyc to work)
lolziac

**Comment by jjelosua** [comment]
Hi @lolziac you are probably facing a race condition where the height is being sent before the child page has finished loading, you have a renderCallback available that you can use for that purpose precisely.

```
function render(width) {
    pymChild.sendHeight();
}

var pymChild = new pym.Child({ renderCallback: render });
```

**Comment by lolziac** [comment]
Hi @jjelosua 
I appended that code snippet but didn't fix it you can check it at [jsfiddle](https://jsfiddle.net/0wvsxda3/), only polling is working (is there any drawback on using polling).

Regards,

**Comment by jjelosua** [comment]
Hi @lolziac let's step back then, how are you building the treemap? the render function should be the one rendering the treemap and after it is actually rendered send `pymChild.sendHeight();` not before.

Do you have control to do that?

Polling is an option but it should not be needed.

**Comment by lolziac** [comment]
Dear jjelosua,

This is the source code of [openspending os-viewer](https://github.com/openspending/os-viewer/tree/master/app)
Yes I have control over it, as I have my own instance.
Furthermore I'm injecting the code at this [embedded page](https://github.com/openspending/os-viewer/blob/master/app/views/layouts/embedded.html) it seems that is the end of visualization as this [page](https://github.com/openspending/os-viewer/blob/master/app/views/pages/embedded.html) where visualizations are drawn extends the previous one.

Regards,
