### ISSUE TITLE
Parent height not updating when i'm using pymChild.sendHeight() 

### ISSUE THREAD

**Issue by Brynskog** [nprapps/pym.js#161]
Hi,

I have an application which exists inside another application that's written by another company. We are both using pym to resize their iframe solution dependent on my content size. A lot of my content is loading with ajax so when the height is set some of the content hasn't finished loading yet. 

This cuts my content off since the parent height already is set when my ajax lists are loading. I try to use pymChild.sendHeight() but the height of the parent is not updating. When i debug and try the sendHeight function in the console the correct height value of the child is returned but still the parent height is'nt updating.

As far as i can see all the code that's needed is in place and the script is working on some of the pages where content is'nt loaded via ajax. 

Any ideas?

**Comment by jjelosua** [comment]
Hi @Brynskog,

There's a render callback on the pym child side that can be used for this kind of scenario, you should use that render callback to launch all your ajax loading and when you know the loading has ended then invoke the `pym.sendHeight()`.

```
function render(width) {
    // Load the child page using Ajax and when that is done invoke:
    pymChild.sendHeight();
}

var pymChild = new pym.Child({ renderCallback: render });
```

**Comment by Brynskog** [comment]
Hi @jjelosua ,

Thank you but unfortunately this does not work for me. But it might be something else causing it. When i look at my pymChild in the debugger i get null or undefined for everything that has to do with the parent, for ex. "parentWidth", "parentUrl", etc..

Shouldn't there be some sort of connection to the parent that i can see in this stage?

Regards,
Simon

**Comment by jjelosua** [comment]
Hi @Brynskog, So the pymChild.sendHeight() never changes the height of the parent? Then it seems that the problem might be with the configuration on the parent side of things, can you provide a simple example of the issue that we can take a look at. Is the parent creating the iFrame from a container with an id? The iFrame needs to be created by Pym.js in order for the communication to happen, if you are not seeing parentWidth or parentUrl it can point us to the idea that the iFrame is not being generated by Pym and if that is the case the communication will not happen....again a code example would be needed for us to try to help you. Can you send pym's initialization code on the parent page?

**Comment by Brynskog** [comment]
Hi @jjelosua ,
Thank you for the support. I've let this go for the moment since the parent isn't part of my company's code but part of another company. We are only providing the child part and i think i've implemented things correctly. The problem only occurs in the test env. and not production so we actually closed the error report.

Regards
Simon

**Comment by harshalone** [comment]
The only workaround or hack I found is
create a hidden button with class update_height and add an event on click sendHeight because no matter what you do renderCallback does not work.
```
<script>
    	
			function update_height(e) { 
			    pymChild.sendHeight();
			}
			
			$('.update_height').on('click', update_height);
			
			var pymChild = new pym.Child();
			
			setTimeout(update_height, 500);
    	
    </script>
```
