### ISSUE TITLE
Does pym have an issue with bourbon/neat?

### ISSUE THREAD

**Issue by khantasha** [nprapps/pym.js#163]
Hi! I'm wondering if there are any known conflicts with using pym and Sass libraries Neat/Bourbon and if there are any fixes? I have something I built using those libraries and pym isn't working. Thank you!

**Comment by ghing** [comment]
Hello! Sorry to hear you're running into issues using pym.  We aren't aware of any issues with pym and frameworks like Neat/Bourbon.  If you have an example of your issue that you can share via something like a gist, codepen or jsfiddle, I'm happy to take a quick look.  However, as we don't use Neat/Bourbon on our team I can't commit to addressing any issues that we do find being a high priority.

**Comment by ghing** [comment]
I'm going to go ahead and close this.  Please feel free to reopen, especially if you have a simplified example of any issues you're seeing that you can share.
