### ISSUE TITLE
Safari - height only correct on resize?

### ISSUE THREAD

**Issue by sporkman** [nprapps/pym.js#164]
I'm not really sure how to troubleshoot, but in Safari (desktop, 11.0), I'm finding that on initial load, the child iframe is way too small in height.  For example, it's at around 290px on load, but should be almost 3x that height to show all the content.  If I resize the window, even just a few pixels, the iframe jumps to the correct size.  Nothing of note is happening in the console log.

Any tips on how to track this down?

**Comment by ghing** [comment]
Hello @sporkman, thanks for your report.  Can you provide a simplified example of the HTML/CSS/JavaScript that reproduces this issue?

**Comment by sporkman** [comment]
Not really - I suspect the complexity of the embedded content probably has something to do with the issue.  The combined site is behind a user/pass (which I can supply privately).  I can show you the content we're embedding though: https://concretewall.no/products/embed?p=3128

Chrome seems fine, Firefox is fine, IE 11 is fine.  Just safari and it's fine on the slightest screen resize.

If that's not enough info, is there a way to give the page a little "kick" after the iframe loads to make it think the window was resized? :)

**Comment by ghing** [comment]
>  is there a way to give the page a little "kick" after the iframe loads to make it think the window was resized?

According to the [docs](http://blog.apps.npr.org/pym.js/), in the child page:

> If you need finer control over resize events, you can invoke pymChild.sendHeight() at any time to force the iframe to update its size.

That might work as a workaround for you on Safari.

**Comment by sporkman** [comment]
I'm a little unclear on the usage - is it possible to force this from the parent side so I don't have to keep asking the person who's working on the embed to do all my debugging?

**Comment by ghing** [comment]
There's not really an API method to force the child to send the height to the parent, but you could use messages for this:

See the "Sending Custom iFrame Events" section in the [docs](http://blog.apps.npr.org/pym.js/).


In the parent page:

```
// ...
pymParent.sendMessage('requestChildHeight');
```

in the child page:

```
pymChild.onMessage('requestChildHeight', function() {
  pymChild.sendHeight();
});
```

However, this is probably unnecessary if you just have the child page call `sendHeight()` at some point when the rendering is complete.

**Comment by alykat** [comment]
This the optimal, recommended way to do it:

> However, this is probably unnecessary if you just have the child page call sendHeight() at some point when the rendering is complete.

A not-ideal-but-sometimes-expedient thing to try if all else fails: You can add a "polling" parameter when you create the `pymChild` object on your child page:

```
var pymChild = new pym.Child({ polling: 500 });
```

Here `pymChild` sends the parent its height every 500ms (or whatever interval you set). It's not ideal b/c it'll just keep running even after you no longer need it. But if you've exhausted all other possibilities, it's a thing to try.
