### ISSUE TITLE
Best way to load pym for an embed widget?

### ISSUE THREAD

**Issue by rathboma** [nprapps/pym.js#166]
Hey guys,

I'm looking to distribute Pym as part of a widget to embed an iframe. However that means I want to make sure that pym is loaded within a function scope, rather than being loaded globally into the page -- Maybe my customer already has pym and double loading could screw it up.

Could you advice the best way to do that? 

One approach I've thought of is to copy the whole pym.js source code within my function and change the `window.pym =` to `myLocalPym =` or something similar.

Any other ideas? Has anyone else done this?

Matthew

**Comment by ghing** [comment]
To address the specific problem of avoiding multiple pyms, I would load the pym.js script asynchronously after checking whether it's already been added:

This would be something like this (untested) code:

```
(function(window, document) {
  var onPymLoaded = function() {
    // Do stuff with pym here.
  };
  // This will be the DOM element for the <script> tag for pym.js, if needed
  var script;

  if (window.pym) {
    onPymLoaded();
    return;
  }

  // Load pym from CDN
  script = document.createElement('script');
  script.onload = onPymLoaded;  
  script.src = 'https://pym.nprapps.org/pym.v1.min.js';
  document.body.appendChild(script);
})(window, document);
```

You may want to check out the implementation of [pym-loader.js](http://blog.apps.npr.org/pym.js/#loader) for more ideas on how to load pym.js asynchronously in the context of various CMSs, but as it is designed to accommodate certain CSMs in the NPR ecosystem, it might not be useful for you to use it directly.
