### ISSUE TITLE
Smooth scrollParentTo functionality

### ISSUE THREAD

**Issue by GitNoise** [nprapps/pym.js#169]
At the moment pym does not support smooth scrolling of the parent as pym uses the window.scroll method to move the parent. 

If Pym instead used element.scrollIntoView (where element would be the body or window element) it would be possible to define if the scroll should be smooth or not using options. 
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

Would this be feasible new feature for pym?

**Comment by thomaswilburn** [comment]
Thank you for filing this issue, and apologies for the lack of response. 

In my tests, using `scrollIntoView()` for an element inside the child frame seems to work fine on its own, without making any additions to Pym (which is great to know, thanks!). Is there a compelling reason to add it to Pym itself, or should we just point people to the standards-based method?
