### ISSUE TITLE
There are merge conflicts in your documentation

### ISSUE THREAD

**Issue by pattiereaves** [nprapps/pym.js#172]
http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/
![image](https://user-images.githubusercontent.com/44990/36332674-6a92a12a-1330-11e8-9cab-807e0517f902.png)
:)

**Comment by jjelosua** [comment]
Oops, thanks for noticing I'll fix that...

**Comment by jjelosua** [comment]
Thanks for flagging @pattiereaves
