### ISSUE TITLE
requesting insecure protocol child, though https is set

### ISSUE THREAD

**Issue by roberthuttinger** [nprapps/pym.js#175]
This regularly occurs when embedding via pym on our site. We're using the 'auto initialization'.

When the page loads, and the parent uses secure protocol, there is an error in pym apparently and it is calling an insecure page. Though the call does indeed include  https.

ie: `<div data-pym-src="https://looking.notthedroids.com/asset">&nbsp;</div>` 

Console:
Mixed Content: The page at 'https://looking.notthedroids.com/parent/of/pymincludedpage' was loaded over HTTPS, but requested an insecure resource 'http://looking.notthedroids.com/asset?initialWidth=855&childId=pym-0-4r77p&parentTitle=Iframe%20Test%20for%20Embedded%20Interactive&parentUrl=https%3A%2F%looking.notthedroids.com%parent%2Fof%2Fpymincludedpage'. This request has been blocked; the content must be served over HTTPS.

Using library:
https://pym.nprapps.org/pym.v1.min.js

**Comment by jjelosua** [comment]
Hi @roberthuttinger, Can you create a simple test to show this behavior I can not reproduce it and looking at pym code I do not see any reason why that should happen. Are you adding more than one embed to the same page? make sure that all of them are https....

**Comment by roberthuttinger** [comment]
Ill see if I can create an instance. Ive only been able to reproduce it on this particular site. But the only triggered error comes from pym when the http site is passed to it.

it is the only pym div on the page.

Stranger is that this is the generated code on the page which is clearly `https`

```
<div data-pym-src="https://looking.notthedroids.com/asset" data-pym-auto-initialized="" id="pym-0-x9941">
  <iframe src="https://looking.notthedroids.com/asset?initialWidth=855&amp;childId=pym-0-x9941&amp;parentTitle=Iframe%20Test%20for%20Embedded%20Interactive&amp;parentUrl=https%3A%2F%2Flooking.notthedroids.com%2Fparent%2Fof%2Fpymincludedpage" width="100%" scrolling="no" marginheight="0" frameborder="0">
  </iframe>
</div>
```

**Comment by roberthuttinger** [comment]
I can believe this is an issue somehow with a code collision on the site. The issue seems to have resolved itself, as it has done in the past. But it is an oddity which I havent been able to nail down. 

I wanted to share here as an issue in case anyone else has hit this as well. #documentation 

For the record, I did nothing to get it working, it just started working magically. As a developer, I dont like magic.
