### ISSUE TITLE
Iframe height set to 150px from child page that renders PHP

### ISSUE THREAD

**Issue by bayreporta** [nprapps/pym.js#176]
I'm having an issue where the parent iframe was always configured to 150px height no matter the child's height, despite trying to poll or callback a pymChild.sendHeight() function. I did some testing and it appears to have something to do with PHP code I have in the child file to load data that populates the page. 

Just wondering if there are known issues regarding height adjustment and PHP on the child. Thanks!

**Comment by bayreporta** [comment]
Nevermind it appears to have something to do with my linked css file. I'm going to dig into it to see what's wrong.

**Comment by bayreporta** [comment]
Found the issue: had my body and html set to height: 100%;

**Comment by tiois** [comment]
Had the same problem using Semantic-UI, which applies a 100% height on <html>.
