### ISSUE TITLE
id parameter specified as number in documentation 

### ISSUE THREAD

**Issue by bolatovumar** [nprapps/pym.js#177]
It says that id should be a number here:
[http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/module-pym.Child.html](http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/module-pym.Child.html)

Line 739 here specifies it as a string:
[http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/pym.js.html#line739](http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/pym.js.html#line739)

Which one is correct?

**Comment by thomaswilburn** [comment]
It is a string. Looks like there's a typo in the docs.
