### ISSUE TITLE
Provide a callback once the iframe is inserted and rendered to prevent lost messages

### ISSUE THREAD

**Issue by rathboma** [nprapps/pym.js#178]
I'm using Vue.js and webpack and I have a workflow whereby I:

1. initialize pym (`this.parent = new Pym.Parent()`)
2. Want to send a message to the child as soon as it is loaded (`this.parent.sendMessage('foo', 'bar')`)

If I do these two things one after the other the iFrame is not rendered, so it does not get the message.

What I'd really like to do is use some sort of `onLoaded` callback, something like:

```js
this.parent.onLoaded((pym) => {
  pym.sendMessage('foo', 'bar')
})

```

I was thinking this could be implemented as a standard message that the child sends whenever it is mounted, that way the parent doesn't have to worry about monitoring the iframe at all.

This workflow is the current workaround, so even if this is not a feature you guys want to add, maybe we could just drop something in the docs?

**Comment by thomaswilburn** [comment]
You could do this by setting a flag and listening for the "height" message, but it might be easier if you configure your child frame to send a message when it is ready to process incoming data. 

child:
```js
var child = new pym.Child();
// attach listeners for foo events
child.sendMessage("hello")
```

parent:
```js
this.parent.onMessage("hello", function() {
  pym.sendMessage("foo", "bar");
});
```
