### ISSUE TITLE
Please add anchor tags to headers on http://blog.apps.npr.org/pym.js/

### ISSUE THREAD

**Issue by benlk** [nprapps/pym.js#181]
This is a documentation issue, not an issue directly on the Pym.js library itself. If I could find a repo serving the page http://blog.apps.npr.org/pym.js/ I'd've filed this issue there.

Please add <a name="example"> anchor tags for all major headings on http://blog.apps.npr.org/pym.js/, so that people can link to specific portions of the documentation.

**Comment by thomaswilburn** [comment]
You can link to the IDs for each section, you don't need an anchor tag. For example: http://blog.apps.npr.org/pym.js/#examples

**Comment by benlk** [comment]
Your solution works for `h2`/`h3`-level things, but not for the `h4` and `h5` items, or specific `div.example-block` examples within http://blog.apps.npr.org/pym.js/#examples, such as if I wanted to send someone a link to the `h4` preceding the bulleted list mentioning `renderCallback` functions.
