### ISSUE TITLE
AMP Compatibility

### ISSUE THREAD

**Issue by benlk** [nprapps/pym.js#182]
Are there plans for Pym.js compatibility with AMPhtml in some fashion?

[`amp-iframe`](https://www.ampproject.org/docs/reference/components/amp-iframe) uses postMessage-based communications to send signals from the child page to the parent page, so if the pymChild could detect that it was loaded in an `amp-iframe` element instead of a usual `pymParent` element, and then send the appropriate messages, that would be nice.

**Comment by thomaswilburn** [comment]
I don't have any plans for it right now, but would be happy to take a look at pull requests for it.

As far as I'm aware, the AMP iframe implementation doesn't really send any identifiable information into the child, it just listens for messages coming from inside the child. This might make it hard to detect what kind of host is including us.

**Comment by westonruter** [comment]
> As far as I'm aware, the AMP iframe implementation doesn't really send any identifiable information into the child, it just listens for messages coming from inside the child. This might make it hard to detect what kind of host is including us.

Would it matter if the child just went ahead and sent the AMP `embed-size` messages in addition to the existing ones? Is detecting an AMP environment really necessary?

**Comment by thomaswilburn** [comment]
Technically, no, you could just send the messages and they should get ignored by Pym hosts. That's what Sidechain does, and anyone who's interested in AMP/Pym cross-compatibility should probably use it instead.

**Comment by thomaswilburn** [comment]
Alternatively, if the AMP project actually cares about working with the community, perhaps they should implement compatibility with legacy Pym messages. There are a lot of static graphics generated with tools like our Dailygraphics Rig that are not going to be upgraded to a new Pym or Sidechain, because it's not reasonable to dig all of them up and republish them. Having AMP support the news industry's de-facto embedding standard would be a real sign of goodwill.

**Comment by westonruter** [comment]
Thanks for the suggestion. Good idea. I'll propose it.

**Comment by westonruter** [comment]
Things are coming full circle: https://github.com/ampproject/amphtml/issues/495

**Comment by westonruter** [comment]
Proposed: https://github.com/ampproject/amphtml/issues/22714

**Comment by thomaswilburn** [comment]
Thank you! I'll be curious to see how that pans out. NPR does not have any intentions at this time of publishing an AMP-compatible site, and there are significant legacy barriers to doing so with our current CMS, but we do know that some of our member stations using WordPress/custom systems are looking into it and would appreciate the support.

Yes, this is not my first time around this particular AMP protocol. In fact, if you all are ever interested in having a conversation about how news sites publish content, particularly on the dataviz/interactive side of things, feel free to reach out. One of the things that was distressing about the project when it launched was that it didn't seem to have consulted with any newsroom developers--hence my filing a bug back then about the surprising omission of support for responsive iframe libraries like Pym, responsive-frame, and Sidechain. That said, I appreciated the team's quick response (then and now).

**Comment by westonruter** [comment]
@thomaswilburn no, thank _you_! Could you subscribe to that issue to answer any technical details that pop up? I tried to answer one based on my limited Pym.js experience.

> we do know that some of our member stations using WordPress/custom systems are looking into it and would appreciate the support

We'd be very happy to support NPR in exploring AMP and WordPress. Feel free to make an introduction.
