### ISSUE TITLE
Optional Fixed Size?

### ISSUE THREAD

**Issue by Linell** [nprapps/pym.js#184]
Is there a way to set an iframe to _not_ be responsive when it's set up via Pym? Right now I've got something like:

```html
    <div
      id="widgetOne"
      data-sbl-widget-id="2"
      data-sbl-sport-id="1"
      data-sbl-gender-id="1"
    ></div>
```

but would like to add something like `data-sbl-responsive=false` so that a width and height set on the div would be respected.

**Comment by thomaswilburn** [comment]
Why wouldn't you just use a regular iframe if you don't want it to be responsive?

**Comment by Linell** [comment]
The idea is to let the customers decide whether or not it will be responsive without having to explain much more than "copy paste this", and if there were an option in Pym I could use all of the same logic for everything.

**Comment by thomaswilburn** [comment]
No, there's no option for Pym to be non-responsive, it's not really a use-case for this library.
