### ISSUE TITLE
Size of iframe is not increasing with dynamic content

### ISSUE THREAD

**Issue by harshalone** [nprapps/pym.js#185]
I have an issue.

I have implemented pmy.js into my project. 

When I run below code in my child file 

```
function send_height(width) {
   pymChild.sendHeight();
}

var pymChild = new pym.Child({ renderCallback: send_height });
```

It does not send the updated height at all

**Comment by harshalone** [comment]
@alykat  @jjelosua

Just so that I explained it correctly:

This is my parent code:

```
<div id="example"></div>
<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
<script>
    var pymParent = new pym.Parent('example', 'child.html', {});
</script>
```

This is my child code

```
function send_height(width) {
   pymChild.sendHeight();
}

var pymChild = new pym.Child({ renderCallback: send_height });
```

Here is the parent url : [https://www.musicdoner.com
](https://www.musicdoner.com
)

As you can see the height of the iframe is not increasing till the end.

**Comment by thomaswilburn** [comment]
Looking at that page, I don't see where you use the render callback at all. You do attach a click listener to a button to update the height, but then it isn't ever actually clicked (at least not programmatically), so I don't think it would ever call `sendHeight()` from there.

We still use `renderCallback` in our older Dailygraphics rig and it continues to work, so I'm pretty sure it's not an issue with Pym. If you can provide a test case in a Gist or some other isolated test environment, that would be very helpful.

**Comment by harshalone** [comment]
Well I am trying that click event because the renderCallback is not working. If you want I can rollback the code to what I have mentioned here above.

**Comment by harshalone** [comment]
@thomaswilburn
The problem is when I run pymChild.sendHeight();
it does not update the height of the new dymanically populated content in the child 

that's why I am trying to come up with other solution. Because when attach an event to a button it sends the height. 

What do you mean by older dailygraphis rig

is renderCallback function has been differed now?

**Comment by thomaswilburn** [comment]
`sendHeight` runs once, but it doesn't necessarily know when the page has changed. If you update the page dynamically, Pym won't know about it, and you'll have to add your own callback in addition to the `renderCallback` hook.

The [Dailygraphics rig](https://github.com/nprapps/dailygraphics) has been using the `renderCallback` option for several years, and as far as I know there haven't been any changes to this functionality.

**Comment by harshalone** [comment]
thanks I have added a hook on my dynamic content and it works fine now
