### ISSUE TITLE
Issues with child navigation example firing only once

### ISSUE THREAD

**Issue by sporkman** [nprapps/pym.js#186]
In the docs, there is an example of using links on the parent to force the child to navigate to a new URL.

On the child pages, this is included:
```
var pymChild = new pym.Child();

pymChild.onMessage('navigate', onNavigateMessage);

function onNavigateMessage(url) {
    window.location.href = url;
}
```
And on the parent:
```
var pymParent = pym.Parent('example', 'child.html', {});

document.getElementById('myLink').addEventListener('click', onLinkClick);

function onLinkClick(e) {
    e.preventDefault();
    pymParent.sendMessage('navigate', e.target.href);
}
```

And that works, I can add a link with an id of "myLink" and the preventDefault works and the navigation of the pym child to a new URL works.

However, if I try to setup a few URLs so that the user can navigate to different child pages, the first click works, but all further attempts at navigation fail with no errors in the console.

I have this in the parent:

```
    var pymParent = new pym.Parent('cw_quotegen', 'https://example.com/foo.php?id=100', {});

    document.getElementById('myLink1').addEventListener('click', onLinkClick);
    document.getElementById('myLink2').addEventListener('click', onLinkClick);

    function onLinkClick(e) {
        e.preventDefault();
        console.log('link hit');
        console.log(e.target.href);
        pymParent.sendMessage('navigate', e.target.href);
    }
```

And my links look like this:

```
<a href="https://example.com/foo.php?id=101" id="myLink1">id of 101</a>
<a href="https://example.com/foo.php?id=102" id="myLink2">id of 102</a>
```
The page loads and the child loads up "https://example.com/foo.php?id=100" as intended. If I click either link, the child navigates to either "https://example.com/foo.php?id=101" or "https://example.com/foo.php?id=102" as expected. If I then click either link after that first navigation, nothing happens other than my console logging that "link hit" and the URL it should be navigating to.

What am I missing? Can I really only navigate once after the initial load?

**Comment by thomaswilburn** [comment]
Do those pages (101 and 102) also add the event listener for navigation? After page load, the child's JS context will be blown away, and the original listener won't be valid anymore.

**Comment by sporkman** [comment]
Yes, the pym child code is identical on all pages (it's actually just one page called with different parameters).  I also setup a simpler test case with 3 static pages with distinct names (foo1.html, foo2.html, etc.) and get the same results. Adding debugging to the child shows nothing on the subsequent hits.

This is in the client now for testing:
```
      console.log('recvd msg');
      console.log(url);
```
edit: actually here's a public test case - very simple example, not even cross-domain:
https://sporklab.com/pym/

**Comment by thomaswilburn** [comment]
So it looks to me like what's happening is that your new child doesn't have an ID set, and as a result it's not matching the message regex that Pym uses to filter its own messages out of everything that can come through `window.onmessage`. Try to set a new ID manually when creating the child, so that it stays consistent, and I think it'll work. Unfortunately, due to the way that Pym constructs itself (as a closure, not as a class or prototype), this can be tough to debug. Sorry about that!

Edit to add: The initial message regex is `/^pymxPYMxcw_quotegenxPYMx(\S+)xPYMx(.*)$/`, and your second window has a regex of `/^pymxPYMxundefinedxPYMx(\S+)xPYMx(.*)$/`. I think configuring your child with an ID of "cw_quotegen" during initialization will work, but I haven't tried that.

**Comment by thomaswilburn** [comment]
You may also want to investigate using Sidechain, our successor to Pym, which uses JSON sentinel values instead of regex matching and probably would be easier to get working.

**Comment by sporkman** [comment]
Are you saying to create the child like this?

`var pymChild = new pym.Child('cw_quotegen');`

**Comment by thomaswilburn** [comment]
I believe it's an object param, so more like `var pymChild = new pym.Child({ id: "cw_quotegen" })`.

**Comment by sporkman** [comment]
That did it!  Thanks. Sidechain looks interesting, but a bit too complex for our one-off use.

Now I just have to wait for someone in another timezone in Norway to update the client code on the real page. :)
