### ISSUE TITLE
Scrolling attribute cannot be reset in IE11

### ISSUE THREAD

**Issue by zinkkrysty** [nprapps/pym.js#187]
Apparently, in IE11, setting the "scrolling" attribute cannot be undone - meaning that if the `scrolling` attribute is set to `no`, then you cannot set it back again to `yes`.

See an example of this behaviour [here](https://codepen.io/zinkkrysty/pen/NWKjNKz).

This means that relying on the ability to toggle it manually at a later point in time, will end up not being consistent cross-browser and introducing a bug. Therefore this plugin should probably not set `scrolling` to `no`, however it should use `style.overflow = 'hidden'`, which can easily be toggled on/off by code.

**Comment by thomaswilburn** [comment]
The whole point of Pym is to not have a scrolling iframe. What's the use case for re-enabling it?

**Comment by zinkkrysty** [comment]
I open a modal, where I have my iframe inside. At some point, the iframe contents becomes larger than the height of my modal, so scrolling needs to happen. I have experienced that is much smoother to disable pym at the point in time (by checking height), and let the iframe fill 95vh for example, with scrollbars of course. The difference in smoothness comes from the fact that I set polling to happen at 200ms to have a small CPU footprint.

Of course, I will enable pym again at the moment the iframe contents gets smaller, and I use a transition animation to make the height change smooth then.

**Comment by thomaswilburn** [comment]
Sounds like you have a solution then.

**Comment by zinkkrysty** [comment]
@thomaswilburn thanks for looking into this. However I do not have a solution except for changing the source code of pym.js locally. I still want the functionality of pym (especially the one for passing messages) however I want more control over when the height is automatically adjusted and how the iframe is styled/modified. I can make a PR where I modify the style instead of the attribute, do you think that could be an option?

**Comment by thomaswilburn** [comment]
We're probably not going to accept a PR or make a change that fundamental given the range of places where Pym is used, unfortunately. You may want to look at other responsive frame libraries--Sidechain, which is Pym-compatible, does not set the scrolling attribute (https://github.com/nprapps/sidechain), and offers some support for message-passing, but it's not really built for IE or other legacy browsers.
