### ISSUE TITLE
would you accept a PR for throttling height postMessage?

### ISSUE THREAD

**Issue by mreinstein** [nprapps/pym.js#188]
I'm keen to use this great library in one of my client's websites. One of their concerns with the existing code is it sends a lot of messages to the parent page. Would you accept something like this in a PR?

```javascript
// send at most 2 per second postMessages to the parent page
var pymChild = new pym.Child({ throttleMessages: 500 });
```

**Comment by thomaswilburn** [comment]
I'm not currently planning on providing more releases to Pym unless there's a security issue--it's stable for our uses. That said, Pym should only be sending messages if you've told it to poll, or if the window is resized. What's the case in which you're getting more than a few messages per second?

**Comment by mreinstein** [comment]
> What's the case in which you're getting more than a few messages per second?

It might be that I misunderstand, but I thought I saw a long-ish stream of postMessage events come in when the iframe size changes. It might just be that I had polling running at too frequent an interval, but I'm wondering if there's value in throttling `postMessage` events that come in during resize events

**Comment by thomaswilburn** [comment]
Depending on your use case it may be good to debounce or throttle costly tasks that are triggered from the event, like D3 re-render, but in our experience there's really no noticeable cost to the message dispatch itself unless polling is set to something ridiculous (<100ms). Treat it like scroll events, basically.

**Comment by mreinstein** [comment]
Sounds reasonable. Thanks for your time!
