### ISSUE TITLE
Is there a blog post or documentation I can use to justify pym's usage?

### ISSUE THREAD

**Issue by mreinstein** [nprapps/pym.js#189]
Having looked at the source code, I'm eager to use pym on the iframe integrations with my various clients. 

I'm getting strong reluctance to include any "3rd party code"

The argument is "this is overkill, why not just fire a postMessage from the iframed page?" My gut feeling is that pym works around a number of "gotchas" in doing this, but I'm unable to articulate _why_ reinventing the iframe postmessage structure is a bad idea.  

Can you point me at a blog post or some kind of defense of pym, in terms of the weird little gotchas it's solving? 🙏

**Comment by thomaswilburn** [comment]
The blog post for Pym lays out the basic case for it: http://blog.apps.npr.org/pym.js/

I don't think Pym particularly works around many gotchas. The appeal for many people is that it's a well-tested solution that's been used by news organizations around the world for years. But it's a pretty simple library. 

If you want something smaller and more modern, I recommend Sidechain, which is our rewrite of Pym for future applications and AMP compatibility: https://github.com/nprapps/sidechain There are also a number of other responsive frame libraries out there, like Frames (https://github.com/rdmurphy/frames/).

I understand the desire to stay away from third-party code, and it's not hard to reinvent what Pym does using messages. I've written two of them myself in the last five years (Sidechain and the Seattle Times `responsive-frame` element). I really think it's a question of how much time you want to spend on duplicating efforts, vs. just plugging in one of these libraries for what's pretty basic functionality.

**Comment by mreinstein** [comment]
> I really think it's a question of how much time you want to spend on duplicating efforts, 
> vs. just plugging in one of these libraries for what's pretty basic functionality.

zero time, ideally. :-) I want to re-use a well-tested library. 

> If you want something smaller and more modern, I recommend Sidechain

Thanks for the links! I'll check 'em out.
