### ISSUE TITLE
iframe srcdoc support?

### ISSUE THREAD

**Issue by brandonrobertz** [nprapps/pym.js#190]
Hello,

I'm looking for some clarification on whether or not pym.js supports iframes where the content is supplied via `srcdoc`.

I noticed there was a pull request implementing this functionality: https://github.com/nprapps/pym.js/pull/121

But it was closed without merge or commenting and I couldn't find any examples or mention of `srcdoc` in the code anywhere.

So I'm curious if someone knows whether or not `srcdoc` is supported.

Thanks!

**Comment by thomaswilburn** [comment]
No, I don't believe it's supported, and we don't plan to offer it.
