### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by elgreg** [nprapps/pym.js#192]
Hello! We're using this at Slate Magazine for a few projects and I was just curious if it is still under active development given that there haven't been any commits in almost 2 years. We don't have any outstanding issues. I'm more just curious about the project in general.

**Comment by thomaswilburn** [comment]
We're not actively doing any development on Pym, although we still use it for our projects. It's feature-complete as far as I'm concerned. Our goal is to gradually transition new projects to nprapps/sidechain, starting with some of our election stuff this year, but there's no schedule for that.
