### ISSUE TITLE
Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by Coop920** [nprapps/pym.js#193]
Hi There!

I was recently given a site that contains this script, https://www.urac.org/directory-accredited-organizations .  However, it doesn't appear to be working at in the console log i see:

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined
    at lib.Child.<anonymous> (pym.v1.js:942)
    at new lib.Child (pym.v1.js:1098)
    at newdirectory?initialWidth=2560&childId=directory-iframe&parentTitle=Directory+of+Accredited+Organizations&parentUrl=https%3a%2f%2fwww.urac.org%2fdirectory-accredited-organizations:46

The code as i see it implemented:

Parent Page:

```
<div id=directory-iframe><iframe src="https://accreditnetadmin.urac.org/UracPortal/directory/newdirectory?initialWidth=2500&amp;childId=directory-iframe&amp;parentTitle=Directory%20of%20Accredited%20Organizations&amp;parentUrl=https%3A%2F%2Fwww.urac.org%2Fdirectory-accredited-organizations" width="100%" scrolling="no" marginheight="0" frameborder="0" height="271px"></iframe></div>
<script src="https://pym.nprapps.org/pym.v1.min.js"></script>
<script>
  var pymParent = new pym.Parent('directory-iframe', 'https://accreditnetadmin.urac.org/UracPortal/directory/newdirectory', {});
</script>
```

Child Page:

```
<script src="https://pym.nprapps.org/pym.v1.js" type="text/javascript"></script>
<script>var pymChild = new pym.Child();</script>
```

In reading over the docs, it appears that everything was setup correctly, but I'm unsure since I've just been given this assignment.

Any insight would be great.

Thanks

**Comment by thomaswilburn** [comment]
Your page loads and initializes Pym inside the head tag, which means that when it tries to find and send the height of the body tag, the browser's HTML parser hasn't created the body yet, and the script fails. Move the Pym-related code in the child page to the bottom of the body tag to give the parser time to work.

**Comment by Coop920** [comment]
Thanks for this.  It did fix my issue, however my child iframe is still not resizing.  I put the following code on the child to manually send the height back to the parent but it doesn't appear to be doing anything. Any thoughts?

```
var pymChild = null;

            document.addEventListener("DOMContentLoaded", function () {
                pymChild.sendHeight();
            });

            pymChild = new pym.Child();
```

Thanks!

**Comment by thomaswilburn** [comment]
I usually turn on the `{ polling: 200 }` option for Pym children instead of manually sending the height on each DOM change. If that doesn't solve your problem, it may be worth making sure that the body of the child page has a measurable offsetHeight--in some cases, CSS changes that set a percentage height will cause the element to size itself to the window, and not vice-versa.
