### ISSUE TITLE
Can not horizontally scroll wide iframes

### ISSUE THREAD

**Issue by TREFZ** [nprapps/pym.js#195]
Iframes injected by pym.js seem to have the `scrolling` attribute set to `"no"`. The result is that wide tables on small mobile screens can not be horizontally scrolled to see the entire table, even if the iframe is wrapped in a `<div>` with a scrollable overflow value.

Maybe scrolling should be optional?

**Comment by thomaswilburn** [comment]
Generally, the point of Pym is to create responsive iframes, meaning those where the content doesn't scroll horizontally and expands vertically. If we allow horizontal overflow, it kind of defeats the purpose.
