### ISSUE TITLE
Wrong height of child found from body element. Please help. Why?

### ISSUE THREAD

**Issue by jasonnicholson** [nprapps/pym.js#196]
### Nonworking example:
child.html lines added:

```
		<script src="../pym.js" type="text/javascript"></script>
		<script>var pymChild = new pym.Child();</script>
```
	
parent.html lines added:
```
		<div id="example"></div>
		<script type="text/javascript" src="../pym.js"></script>
		<script>var pymParent = new pym.Parent('example', 'child.html', {});</script>
```
		
		
For the nonworking example, the iframe defaults to a height of 150px. Line 941 from pym.js reads the body element at 150px. Why?

### Working example:
child.html
```
		<body><div id=myContent class="content"> ...
		<script src="../pym.js" type="text/javascript"></script>
		<script>
			var pymChild = new pym.Child();
			var height = document.getElementById('myContent').offsetHeight.toString();
			pymChild.sendMessage('height', height);
		</script>
```
		
parent.html
		same as a nonworking example. Basically no change in the code.
		
I add an id of myContent to a div element enclosing all the same elements that the body element encloses. I send a message to the parent with the height from the div element and everything seems to work. Why do I have to do this? Why doesn't getting the height of the body element work?

Files of the examples are attached.
[examples.zip](https://github.com/nprapps/pym.js/files/5960363/examples.zip)

**Comment by thomaswilburn** [comment]
Your body has a height of 100% in the non-working example, which means that it sizes itself to the window. In this case, that's the iframe's default height of 150px.

**Comment by jasonnicholson** [comment]
Thank you! That is clear. I appreciate the help!
