### ISSUE TITLE
Scrollbar quirk in OS X: Inaccurate width calculated on initial load

### ISSUE THREAD

**Issue by alykat** [nprapps/pym.js#56]
Found an interesting quirk re: scrollbars in OS X and calculating browser width.

If the content on the page is super-short before the iframe loads (and therefore the page has no scrollbar initially), and you have one of these OS X scrollbar settings set:

![image](https://cloud.githubusercontent.com/assets/491318/3785571/5dfed0a8-19c6-11e4-9134-29fbc2f21d3c.png)
![image](https://cloud.githubusercontent.com/assets/491318/3785575/69b604ac-19c6-11e4-82a8-50020b2970fe.png)

Pym will calculate the width of the browser and without taking into account the width of the scrollbar. So, on initial load, a graphic might be drawn about 15px too wide (but will fix itself onresize).

To replicate, on a Mac, go to System Preferences > General and try one of the two settings above. Then test this URL:

http://apps.npr.org/dailygraphics/graphics/salt-yeast-alcohol-alastair/

When it's misbehaving, the "4" at the end of the x-axis gets cut off / does not appear.

Noted in OS X 10.9.3 in Chrome and Firefox. (Didn't check Safari.)

(Thanks to @dannydb for helping to identify what was causing the problem.)

**Comment by carloslaramad** [comment]
Hello.

¿How can I set a static height to the iframe, and make to scroll inside?
