### ISSUE TITLE
body with height: 100% doesn't work with sendHeight()

### ISSUE THREAD

**Issue by infoactive** [nprapps/pym.js#64]
Child documents which have height: 100% set on their body (which many .css reset libraries do), accessing the document height with: 

``` javascript
 document.getElementsByTagName('body')[0].offsetHeight.toString();
```

will return the initial height of the iframe regardless of additional calls to sendHeight(). 

A more robust height calculation might be:

``` javascript
var body = document.body,
  html = document.documentElement;

var height = Math.max( body.scrollHeight, body.offsetHeight,
          html.clientHeight, html.scrollHeight, html.offsetHeight );
```

as referenced here: http://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript.

I'm not sure that this would cause an issue to existing height calculations, but I'd be happy to go ahead and create a pull request if you guys think that this approach is good.

**Comment by daltonrooney** [comment]
Thanks @infoactive, I was experiencing this very problem. It was caused by the sticky footer mixin from Compass in my case. Your height calculation helped, although it did not kick in until I resized the window. I added `pymChild.sendHeight();` to the `$(window).load()` event which did the trick.

Chrome 40, OS X 10.10.2

**Comment by wshaver** [comment]
I'm seeing this same issue, and hotfixing in my code for now...

**Comment by lorenwest** [comment]
Same issue here - my client iframe is an angular app with body height 100%, and sendHeight always sends 0 to the containing frame.  Using the @fizz fork until this resolution can make it's way into pym proper.  Thanks @fizz!
