### ISSUE TITLE
eventListener is not removed after window redraw

### ISSUE THREAD

**Issue by lenciel** [nprapps/pym.js#73]
I have 3 entries on sidebar and click each of them will trigger an ajax loading of  `<div id='iframe-container'>` element and an iframe loaded into that container.

By saying 'an iframe loaded into that container' I'm actually use the `autoinit` way and the `{{ web_app_url }}` and `{{ web_app_key }}` is unique for each entry:

```
    <div data-pym-src="{{ web_app_url }}" id="iframe-container-{{ web_app_key }}">
    </div>
```

So, after three entries are clicked, because we have the code below on line 188-192:

```
            // Add an event listener that will handle redrawing the child on resize.
            var that = this;
            window.addEventListener('resize', function() {
                that.sendWidth();
            });
```

every time the windows is resized, three sendWidth() event will be send, and two of them will fail because `that` is already null.

Is there anything I missed and what is the suggested way for this scenario?
Thanks a lot.

**Comment by onyxfish** [comment]
Hi Lencil, sorry for the long delay in replying. I want to make sure I'm understanding correctly. Two questions:

1) Each time you render you iframe are you overwriting the old one?
2) How are you triggering autoinit if your page is already rendered? Are you calling `_autoInit` directly?

**Comment by lenciel** [comment]
Hi, @onyxfish, 

> 1) Each time you render you iframe are you overwriting the old one?
   
No, I'm not overwriting the old one. Because I have the requirement that, let's say user is currently on iframe A and he fill some form fields, then he/she switch to iframe B, and when he/she get back to iframe A, the fields filled earlier should be there. 

> 2) How are you triggering autoinit if your page is already rendered? Are you calling _autoInit directly?

I'm using Django. And when user click the sidebar, the template engine will render the same template with different `web_app_url` and `web_app_key` and after the template rendered, since pym.js is loaded the `data-pym-src` will be triggered.

```
    <div data-pym-src="{{ web_app_url }}" id="iframe-container-{{ web_app_key }}">
    </div>
```
