### ISSUE TITLE
Q: How to jump to a certain anchor inside <iframe> with pym.js

### ISSUE THREAD

**Issue by miohtama** [nprapps/pym.js#81]
I am not sure if this falls into a new feature or a question category, but I hope the authors can clarify me.

Requirement: I have several `<a id="">` anchor points inside the loaded `<iframe>`. I'd like to "jump", or scroll the parent page, to a specific position after `<iframe>` completes the loading.

As I can see this problem could be divided to the following parts

* Catch `<iframe>` loaded event
* Extract anchor coordinates and sent them to the parent frame (how?)
* Parent frame scrolls the page to the coordinates + `<iframe>` offset

If you know any cleverer way to do this or if there is some sort of native support please let me know. Otherwise I'll post my code here after I have wrapped my head around this.

**Comment by alykat** [comment]
You might be able to do this with cross-frame communication built into Pym. See this thread:
https://github.com/nprapps/dailygraphics/issues/44

**Comment by miohtama** [comment]
Thanks @alykat 

Furthermore if someone is interested in the use case is here:

https://libertymusicstore.net/

If you click any of the albums it should jump to the album within the artist page, but currently it doesn't do it.

**Comment by onyxfish** [comment]
Hi @miohtama, I've just implemented `pymChild.scrollParentTo` and `pymChild.navigateParentTo`, which should address your needs. These should make it into a release sometime soon, but if you need them urgently you should be able to use what's on master. I'll leave this ticket open until we write some documentation for the new methods.

**Comment by russellgoldenberg** [comment]
It looks like new implementation sends an anchor (that exists in the parent dom) from child to parent, and jumps parent to that anchor. It sounds like @miohtama is looking for a way to jump the iframe to another anchor within the iframe. 

If I am understanding correctly, they are two different problems. My current workaround for the other problem is to grab the offset position of the desired element within child on click, then send a message to parent with that value. Then set scrollTop of parent = that value + iframe offset of parent.

**Comment by onyxfish** [comment]
Ah, I see. Yes, I had misunderstood the original problem. That approach sounds reasonable. I suppose it would be possible to implement this as a core part of pym. If somebody takes a whack at it feel free to send a pull request. It's unlikely to rise to the top of our list of priorities until we have a graphic that needs it.

**Comment by russellgoldenberg** [comment]
I stumbled across the need for it inadvertently, and probably won't be using again. I suppose it depends on the philosophy. I am developing a faux fullscreen app that really lives inside an article from our CMS that has everything else hidden, mostly for business reasons...

**Comment by miohtama** [comment]
@onyxfish - Looks good! My problem is super non-urgent, so I haven't been looking into this, but looks like some extra message passing and `pymChild.scrollParentTo()` could cut it.
