### ISSUE TITLE
more safe message validation

### ISSUE THREAD

**Issue by russellgoldenberg** [nprapps/pym.js#92]
On our site, rogue messages can be sent to the iframe, sometimes from a whiltelisted domain, that are out of my control.  They throw the error ```Uncaught TypeError: e.data.match is not a function``` because the e.data is an object. Thoughts on adding this to _isSafeMessage?

```javascript
var _isSafeMessage = function(e, settings) {
    if (settings.xdomain !== '*') {
        // If origin doesn't match our xdomain, return.
        if (!e.origin.match(new RegExp(settings.xdomain + '$'))) { return; }
    }

    // If message is not a string, return.
    if(typeof e.data !== 'string') { return; }

    return true;
};
```

**Comment by onyxfish** [comment]
Fixed with merge of #89.
