### ISSUE TITLE
Get parent .scrollTop() from click within child

### ISSUE THREAD

**Issue by acoffin** [nprapps/pym.js#94]
I'm having an issue with positioning a popup window within the child so that it's centered in the viewport. Normally I'd used a fixed position, but since the child iframe is its own document, fixed positioning acts more like absolute positioning in the parent.

I've been looking at the API documentation on messaging between the parent and child but can't seem to figure out how to get a click action within the child to retrieve the .scrollTop() information from the parent and apply it to the css of my popup in the child. Am I missing something here?

**Comment by onyxfish** [comment]
Hmmm, it doesn't *sound* like you're missing anything. The messaging solution seems like the right one. Have you looked at the [events](https://github.com/nprapps/pym.js/tree/master/examples/events) code example?

**Comment by acoffin** [comment]
I'm likely overlooking something, but I think using pymChild.scrollParentTo(); instead will be a simpler solution.
