### ISSUE TITLE
Fully-qualified URL, how to use URL that does not end with a .html

### ISSUE THREAD

**Issue by schikulski** [nprapps/pym.js#96]
Trying to implement pym.js to my site. I have the following code:

```
<div id="example"></div>

    <script type="text/javascript" src="http://ferdigsnakkav2.dev.joss.as/app/themes/ferdigsnakka/assets/js/plugins/pym.js"></script>
    <script>
        var pymParent = new pym.Parent('example', 'http://ferdigsnakkav2.dev.joss.as/embed/embedtest', {});
    </script>

</div>
```

This shows the iframe but does not resize. When I change the URL to something like _http://example.com/test.html_ it works as expected. 

So the question is. How can I use pym.js with my _http://ferdigsnakkav2.dev.joss.as/embed/embedtest_ URL?

**Comment by eads** [comment]
This is very curious to me (I'm helping take over some of the team's pym development and there's many pym things I don't know yet). I am going to take a look and circle back to this. We'd like to have real tests and this feels like one to test for sure. 

I think there's a small chance it's the lack of a trailing slash in your example -- most webservers issue a redirect if there's no trailing slash, and maybe that redirect is what's causing the trouble. I believe the iframe will report "ready" on the redirect response, not on the second response, which could cause the responsive event handling not to correctly bind. Have you tried it with a trailing slash? 

Most likely it's something else, but I'd like to eliminate that possibility.

**Comment by schikulski** [comment]
I've not tried it with a trailing slash, but you might be right. It's a WordPress-site in production but I ended up using a different approch, so I'm afraid I'm not able to test it at this point.
