### ISSUE TITLE
pym 0.4.3(4) is breaking (intermittently, but most of the time) on (newly released?) CorePub

### ISSUE THREAD

**Issue by coreyhaines** [nprapps/pym.js#97]
So, it appears that 0.4.3 has started breaking intermittently on one of our clients sites, Michigan Radio, and is throwing the exception copied in below (ugly, I know). Here's the Michigan Radio page:
http://michiganradio.org/post/what-questions-do-you-have-about-mental-health-issues-michigan#stream/0
**note** I'm having him switch the embed to using the newer version (0.4.4), as that seems to be fixing it.

It appears that 0.4.4 does work. It looks like a new push of core publisher was done recently, could this be the cause?

The weird thing is that it seems to be intermittent, refreshing the page causes our module to not appear (hard refresh usually brings it back).

**question** Is there a good URL to pull the latest version from? I see that the page has
http://blog.apps.npr.org/pym.js/dist/pym.min.js
as the latest, but the cdnjs link doesn't seem to have a /dist, just specific versions a la
https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.3/pym.min.js
https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.4/pym.min.js

Or should we definitely host it ourselves. If so, are we alerted when a new version comes out, any compatibility issues with core publisher, etc?

Help.

```Uncaught Error: Mismatched anonymous define() module: function (){var a="xPYMx",b={},c=function(a){var b=new RegExp("[\\?&]"+a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]")+"=([^&#]*)"),c=b.exec(location.search);return null===c?"":decodeURIComponent(c[1].replace(/\+/g," "))},d=function(a,b){return"*"===b.xdomain||a.origin.match(new RegExp(b.xdomain+"$"))?!0:void 0},e=function(b,c,d){var e=["pym",b,c,d];return e.join(a)},f=function(b){var c=["pym",b,"(\\S+)","(.+)"];return new RegExp("^"+c.join(a)+"$")},g=function(){for(var a=document.querySelectorAll("[data-pym-src]:not([data-pym-auto-initialized])"),c=a.length,d=0;c>d;++d){var e=a[d];e.setAttribute("data-pym-auto-initialized",""),""===e.id&&(e.id="pym-"+d);var f=e.getAttribute("data-pym-src"),g=e.getAttribute("data-pym-xdomain"),h={};g&&(h.xdomain=g),new b.Parent(e.id,f,h)}};return b.Parent=function(a,b,c){this.id=a,this.url=b,this.el=document.getElementById(a),this.iframe=null,this.settings={xdomain:"*"},this.messageRegex=f(this.id),this.messageHandlers={},c=c||{},this._constructIframe=function(){var a=this.el.offsetWidth.toString();this.iframe=document.createElement("iframe");var b="",c=this.url.indexOf("#");c>-1&&(b=this.url.substring(c,this.url.length),this.url=this.url.substring(0,c)),this.url.indexOf("?")<0?this.url+="?":this.url+="&",this.iframe.src=this.url+"initialWidth="+a+"&childId="+this.id+b,this.iframe.setAttribute("width","100%"),this.iframe.setAttribute("scrolling","no"),this.iframe.setAttribute("marginheight","0"),this.iframe.setAttribute("frameborder","0"),this.el.appendChild(this.iframe);var d=this;window.addEventListener("resize",function(){d.sendWidth()})},this._fire=function(a,b){if(a in this.messageHandlers)for(var c=0;c<this.messageHandlers[a].length;c++)this.messageHandlers[a][c].call(this,b)},this._processMessage=function(a){if(d(a,this.settings)){var b=a.data.match(this.messageRegex);if(!b||3!==b.length)return!1;var c=b[1],e=b[2];this._fire(c,e)}},this._onHeightMessage=function(a){var b=parseInt(a);this.iframe.setAttribute("height",b+"px")},this._onNavigateToMessage=function(a){document.location.href=a},this.onMessage=function(a,b){a in this.messageHandlers||(this.messageHandlers[a]=[]),this.messageHandlers[a].push(b)},this.sendMessage=function(a,b){this.el.getElementsByTagName("iframe")[0].contentWindow.postMessage(e(this.id,a,b),"*")},this.sendWidth=function(){var a=this.el.offsetWidth.toString();this.sendMessage("width",a)};for(var g in c)this.settings[g]=c[g];this.onMessage("height",this._onHeightMessage),this.onMessage("navigateTo",this._onNavigateToMessage);var h=this;return window.addEventListener("message",function(a){return h._processMessage(a)},!1),this._constructIframe(),this},b.Child=function(b){this.parentWidth=null,this.id=null,this.settings={renderCallback:null,xdomain:"*",polling:0},this.messageRegex=null,this.messageHandlers={},b=b||{},this.onMessage=function(a,b){a in this.messageHandlers||(this.messageHandlers[a]=[]),this.messageHandlers[a].push(b)},this._fire=function(a,b){if(a in this.messageHandlers)for(var c=0;c<this.messageHandlers[a].length;c++)this.messageHandlers[a][c].call(this,b)},this._processMessage=function(a){if(d(a,this.settings)){var b=a.data.match(this.messageRegex);if(b&&3===b.length){var c=b[1],e=b[2];this._fire(c,e)}}},this._onWidthMessage=function(a){var b=parseInt(a);b!==this.parentWidth&&(this.parentWidth=b,this.settings.renderCallback&&this.settings.renderCallback(b),this.sendHeight())},this.sendMessage=function(a,b){window.parent.postMessage(e(this.id,a,b),"*")},this.sendHeight=function(){var a=document.getElementsByTagName("body")[0].offsetHeight.toString();h.sendMessage("height",a)},this.scrollParentTo=function(a){this.sendMessage("navigateTo","#"+a)},this.navigateParentTo=function(a){this.sendMessage("navigateTo",a)},this.id=c("childId")||b.id,this.messageRegex=new RegExp("^pym"+a+this.id+a+"(\\S+)"+a+"(.+)$");var f=parseInt(c("initialWidth"));this.onMessage("width",this._onWidthMessage);for(var g in b)this.settings[g]=b[g];var h=this;return window.addEventListener("message",function(a){h._processMessage(a)},!1),this.settings.renderCallback&&this.settings.renderCallback(f),this.sendHeight(),this.settings.polling&&window.setInterval(this.sendHeight,this.settings.polling),this},g(),b}
http://requirejs.org/docs/errors.html#mismatch
B	@	js_0zLPjMtKCAjb24C3jwPrWXUq6M865Iuwe5-4JC9bgBk.js:1
w	@	js_0zLPjMtKCAjb24C3jwPrWXUq6M865Iuwe5-4JC9bgBk.js:1
(anonymous function)	@	js_0zLPjMtKCAjb24C3jwPrWXUq6M865Iuwe5-4JC9bgBk.js:1
```

**Comment by coreyhaines** [comment]
Looks like this is the cause of the error: http://requirejs.org/docs/errors.html#mismatch

**Comment by coreyhaines** [comment]
This is the embed code they are using:
```
<p class="curiosity-module" data-pym-src="http://micurious.michiganradio.org/curiosity_modules/92" id="hwkpr">&nbsp;</p> <script src="https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.3/pym.min.js"></script>
```
(using p tags, since core publisher strips away empty divs)

**Comment by coreyhaines** [comment]
I used Charles Proxy to replace the call to 0.4.3 with a call to 0.4.4 (http://blog.apps.npr.org/pym.js/dist/pym.min.js), and it seems to work better (didn't see errors popping up). I also noticed, though, that
https://cdnjs.cloudflare.com/ajax/libs/pym/0.4.4/pym.min.js
loads up 0.4.3, not 0.4.4 o_O

**Comment by coreyhaines** [comment]
Moving to 0.4.4 (http://blog.apps.npr.org/pym.js/dist/pym.min.js) didn't work. Still breaking. ARGH! :sob: ```http://michiganradio.org/post/what-questions-do-you-have-about-mental-health-issues-michigan#stream/0```

**Comment by coreyhaines** [comment]
pinging @onyxfish on this. Kind of urgent-ish.

**Comment by onyxfish** [comment]
Hey Corey, so I can't dive in and debug this thoroughly right now, but here's what I know:

These sorts of on-again/off-again issues are usually caused by a race condition in loading assets. After chatting with @eads our best guess for what's going on would be a race condition between the libraries your graphic depends on for rendering and the pym onload hook first firing. As I understand it you might be able to tell require that pym depends on all of your other assets in order to ensure it loads last.

A couple other notes:
* I can't get the pym embed to load at all in either FF or Chrome, but some of my coworkers do see it...
* Somebody else added the require.js support. I've never used it, so I'm not in a great position to debug it, however, there is a require.js FAQ entry that specifically addresses this error message: http://requirejs.org/docs/errors.html#mismatch

Does any of that help?

**Comment by onyxfish** [comment]
From that requirejs page: "Be sure to load all scripts that call define() via the RequireJS API. Do not manually code script tags in HTML to load scripts that have define() calls in them.". Is this a conflict between pym being loaded via script tag and other assets being loaded with require? Is it being double-loaded? I do see a pym script tag on the page.

**Comment by coreyhaines** [comment]
Hey, @onyxfish 

Thanks!

So, it seems like the new CorePub is using requirejs, and our script tag is causing it to choke?

On the page I sent, it loads intermittently, usually will come back with a hard refresh (cmd+shift+r), but goes away with another refresh. It definitely does seem like a race condition.

I saw that require.js error page, and I can look at the CorePub page to see what the situation is with their require.js stuff.

Do you all have any contacts on the CorePub team to help debug this? It just started today, and my contact at Michigan Radio (who is embedding our widget) said that they pushed a new version last night.

I'm actually using pym.js to load up an iframe, not a graphic. It does have a widget in there (you can see it on this page: http://kalw.org/  it is the "What's Up" widget on the right sidebar.
I don't think it is interacting with the script that is in my iframe, as it isn't even being rendered onto the page, so any scripts in my iframe aren't loading. It seems like it is interfering with something on the CorePub page.

This is the code we give them to embed:
```
<p class="curiosity-module" data-pym-src="http://micurious.michiganradio.org/curiosity_modules/92" id="hwkpr">&nbsp;</p> <script src="http://blog.apps.npr.org/pym.js/dist/pym.min.js"></script>
```

**Comment by coreyhaines** [comment]
As far as I can tell, pym.js is only being loaded once on the page. I don't see the CorePub page loading it all.

**Comment by onyxfish** [comment]
Well, crap. It sounds like the Core Publisher switch to require.js has screwed things up. We do have a contact on the Core Publisher team. I'll send this thread along and see what they think.

**Comment by coreyhaines** [comment]
Please do! Thanks!!! 

If they want to get in touch with me, please let me know. So far, it is just the one CorePub-based customer, but I imagine if they roll out this stuff through any of our other customers, we're going to hit the same problem.

Please let me know if there is anything I can do speed this along. THANKS!

**Comment by onyxfish** [comment]
Okay I've reached out. We'll try to take a closer look at this on our end in the morning.

**Comment by coreyhaines** [comment]
So, interestingly, KALW (http://kalw.org/) has it embedded, as well, but doesn't seem to have the same problem. It does look like their CorePub is using require.js, as well. That might help debug.

**Comment by coreyhaines** [comment]
So, I verified it is the require.js by stripping out the support for it. This fixed the problem. Here's the top
```
(function(factory) {
  window.pym = factory.call(this);
})(function() {
```
So, I'm hosting a copy of my code on S3 and serving it. This at least is a temporary fix. Looking forward to hearing more about a final solution, though.

I hope we hear from CorePub team soon.

**Comment by onyxfish** [comment]
So here's the latest:

"Our persistent player (which michiganradio is using) uses require.js which seems to be conflicting with the pym code."

As absurd as it seems, there doesn't seem to be a simple solution for having two modules on the same page that both define anonymous namespaces. The proposed solution I'm finding on most threads is to give one module an "explicit" name, however, its not at all clear how doing this for pym would affect folks who are using it in an existing require.js workflow.

**Comment by coreyhaines** [comment]
Good to know that it is the persistent player, so I can warn our other clients. Mark, at Michigan Radio, mentioned that he tried embedding the module on his front page, but the streaming stopped working. This might be the reason. I'll keep him (and others) on version to pull it out of the require.js flow. o_O

I tried fooling around with it last night to add an explicit name, but was having troubles. I'm not that experienced with require.js, and it started feeling like a hole I didn't need to go down.

This is definitely a bit of a quandry. For now, I'll fork the repo and make the changes to remove the require.js stuff and just use that fork for Hearken embeds.

Let me know if I can help with more information. Can point to other stations that are embedding on CorePub, if you want to look at theirs. Also, Huzzah for Charles Proxy for testing.

**Comment by onyxfish** [comment]
Thanks for being so thorough, Corey. I was going to suggest forking until we come up with a better solution. I've reached out on Twitter to hopefully get some suggestions from folks who know this architecture better than me. I'll let you know when we come up with something.

**Comment by coreyhaines** [comment]
Thanks a lot!

**Comment by onyxfish** [comment]
So I've logged into the Core Publisher test instance and can confirm that:

1) pym embeds work fine with persistent player off
2) they break with it on
3) require.js is being loaded with the persistent player assets package
4) defining a module name for pym doesn't fix anything

So I'm 80% sure the only global solutions to this problem are to either yank require.js support from pym or maintain two versions.

**Comment by coreyhaines** [comment]
Sounds about right. Is require.js support needed or was it just a "well, we may as well, because, you know, javascript!" :)

Personally, I'd be really happy if it just initialized on document load instead of right away. :) 
https://github.com/nprapps/pym.js/blob/master/src/pym.js#L582

**Comment by coreyhaines** [comment]
So, forked and am hosting from my own S3 bucket now. I'll let you know if I make any changes, send a PR, or something. For now, I just stripped out the two calls to a loader (including require.js).
https://github.com/wearehearken/pym.js/blob/master/src/pym.js#L8-L10

**Comment by brentajones** [comment]
I updated to the Hearken version of Pym, but am still having issues on Core Publisher.

###Behavior:
* Intermittent.
* Different in different browsers.
    * On Firefox and Chrome (in both OSX and Windows), if you click through to an article with an iFrame from the home page, the story will not have the iFrame. If you reload the story, the iFrame will appear.
    * In Safari, if you click through to the story, the iFrame is not there. If you reload the story, the iFrame shows up momentarily before what looks like a page reload. After the page reload, the iFrame is gone. Sometimes this auto-reload happens in Chrome as well, but not as consistently as Safari.

###Notes:
* During the auto-reload on Safari as well as the initial click-through from the home page on Chrome and Firefox, a thin blue progress bar appears at the top of the viewport (not the normal location bar of the browser, but at the very top of the viewport, no matter where it's scrolled to). This auto-reload appears to not happen on a manual refresh of the page in Chrome or Firefox, but it does on Safari.
* After the automatic reload, the <p> and <script> tags are both gone when viewing the source code.

###Examples:
* [Map](http://news.stlpublicradio.org/post/mapped-peter-fischers-legacy-enriches-art-st-louisans-can-enjoy#stream/0). A map should appear just above the header "DONALD BAECHLER". To test the click-through behavior, [here's a tag page](http://news.stlpublicradio.org/term/citygarden#stream/0).
* [Chart](http://news.stlpublicradio.org/post/report-attendance-gap-starts-early-erodes-students-success#stream/0). A block histogram should appear just above the header "Murky National Picture". To test the click-through behavior, [here's a tag page](http://news.stlpublicradio.org/term/accounted).

####Note:
The chart is using a version of pym provided to me by Jim Hill at KUNC after I mentioned this problem to him on Twitter. The map should be using the Hearken version.

**Comment by coreyhaines** [comment]
Brent,

When the iframe does not show up, do you see any errors in the dev console?
I haven't seen it not show up, so I'm wondering if there is some bug I
haven't found yet.

Also, is the page where it doesn't show up publicly accessible? I'd love to
take a look.

**Comment by brentajones** [comment]
The two examples are live and published, and the behavior I described is happening there for me right now. I'll get some error logs.

**Comment by brentajones** [comment]
[Log in Safari](https://gist.github.com/brentajones/e70824cc886daff133ef).

[Log in Safari with auto-reload](https://gist.github.com/brentajones/ca37916f9fd08b963892).

[Log in Chrome](https://gist.github.com/brentajones/ce3b564833677054b05b).

All these are in OSX. I looked at the console on a coworker's windows machine and got something completely different, so I have no idea what's going on.

The errors in Safari seem to be occurring on all pages for me. Maybe it's my setup (although the disappearing iFrames are definitely happening elsewhere).

**Comment by onyxfish** [comment]
Hey all,

Brent, I'm not sure if your issue is exactly the same as Corey's, but just to update you both on where were at with CP pym issues: its bad. The problems been amplified tremendously because we've learned we are facing all the same problems on NPR.org which is about to switch to a PP of its own later this year. So, we're scrambling to fix it on the main site, which means that fixing it for member stations has taken a backseat. Sadly, whatever fix we find for the main site is almost certain *not* to work with CP because of the Javascript limitations that require us to use autoinit. Moreover, the solution is turning out to be *very* complicated, so its taking us a long time to get it sorted.

I have no idea when we're going to back to fix this. At this point I'm only speculating that we will be able to fix it at all. Autoinit was always a hack and unfortunately the reality of that has come back to bite us.

Sorry to be depressing. I've been wrestling with this for two weeks now and still don't have a firm solution for our own content. I'll update you once I know more.

C

**Comment by brentajones** [comment]
Another data point (particularly for Corey and Hearken), here's WYSO:

On Safari, if I go to the Hearken page directly (i.e. without visiting another Core Publisher page first), I see this: http://imgur.com/KT2l9aG

If I go to any other page, like the homepage, then click through to the Hearken page, I get this: http://imgur.com/LW0WiT6

**Comment by coreyhaines** [comment]
Awesome, thanks, Brent! I just heard from them that there is a weirdness.
Going to be taking a look. Frustrating, to say the least. :)

**Comment by coreyhaines** [comment]
Okay, this is weird. If you go to the wyso curious page from their home page, then there is a javascript error:
```Uncaught TypeError: Cannot read property 'postMessage' of null```
on the CorePub stuff. So, javascript stops running, and pym.js doesn't run to create the iframe.
If you go directly to the page, then the error doesn't happen, so pym.js runs fine and creates the iframe.

**Comment by coreyhaines** [comment]
I appear to have fixed this on my branch. I created a PR to show what I did. https://github.com/nprapps/pym.js/pull/105
