### ISSUE TITLE
Set iframe id and name attributes

### ISSUE THREAD

**Issue by ngelx** [nprapps/pym.js#99]
Hi, first of all, thanks for this nice lib.

I'm trying to integrate this lib with another one (porthole.js) that requires that the iframe got the id and name set. 
There is any easy way to do it? 

Thanks in advance,

**Comment by eads** [comment]
Hi there. Sorry for the very slow reply -- one of our devs moved on to another job and then election season started. See additional comments on your PR.

**Comment by jjelosua** [comment]
Fixed in v1.0.0 release eb8d39c
